import type { Metadata } from "next";

import { Header, Footer } from "@/components/global";
import "./globals.css";
import { favorit, inter } from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${favorit.variable} font-inter`}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow flex flex-col">{children}</main>
        </div>
      </body>
    </html>
  );
}
